#!/usr/bin/env bash
# Install Spectre Desktop as a user-local desktop application.
#
# Usage (from the project root):
#   ./install.sh
#   ./install.sh --check   # deps only, no install

set -euo pipefail

APP_ID="com.digitizable.spectre-desktop"
APP_NAME="Spectre Desktop"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
LAUNCHER_NAME="spectre-desktop"
LAUNCHER_PROJECT="$PROJECT_ROOT/bin/$LAUNCHER_NAME"
LAUNCHER_USER="${XDG_BIN_HOME:-$HOME/.local/bin}/$LAUNCHER_NAME"
DESKTOP_SRC="$PROJECT_ROOT/data/${APP_ID}.desktop.in"
DESKTOP_DST="${XDG_DATA_HOME:-$HOME/.local/share}/applications/${APP_ID}.desktop"
ICON_SRC="$PROJECT_ROOT/data/icons/hicolor/scalable/apps/${APP_ID}.svg"
ICON_DST_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
ICON_DST="$ICON_DST_DIR/${APP_ID}.svg"
VENV_DIR="$PROJECT_ROOT/.venv"
CHECK_ONLY=0

if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
fi

info()  { printf '==> %s\n' "$*"; }
warn()  { printf 'warning: %s\n' "$*" >&2; }
die()   { printf 'error: %s\n' "$*" >&2; exit 1; }

check_cmd() {
  command -v "$1" >/dev/null 2>&1
}

check_python_gi() {
  local py="${1:-python3}"
  "$py" - <<'PY'
import sys
errors = []
try:
    import gi
except ImportError as e:
    print("FAIL: python3-gi not importable:", e)
    sys.exit(1)

for ns, ver in (("Gtk", "4.0"), ("Adw", "1")):
    try:
        gi.require_version(ns, ver)
        mod = __import__("gi.repository", fromlist=[ns])
        getattr(mod, ns)
        print(f"OK: {ns} {ver}")
    except Exception as e:
        print(f"FAIL: {ns} {ver}: {e}")
        errors.append(ns)

sys.exit(1 if errors else 0)
PY
}

print_dep_help() {
  cat <<'EOF'

Missing system packages for GTK4 + libadwaita (Debian/Ubuntu/Mint):

  sudo apt update
  sudo apt install -y \
    python3 python3-venv python3-gi python3-gi-cairo \
    gir1.2-gtk-4.0 gir1.2-adw-1 \
    libadwaita-1-0 libgtk-4-1

Then re-run:  ./install.sh
EOF
}

info "Project root: $PROJECT_ROOT"

if ! check_cmd python3; then
  die "python3 not found"
fi

info "Checking GTK4 / libadwaita Python bindings (system Python)…"
if ! check_python_gi python3; then
  print_dep_help
  exit 1
fi

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  info "Dependency check passed."
  exit 0
fi

if [[ ! -d "$VENV_DIR" ]]; then
  info "Creating virtualenv with system site packages…"
  python3 -m venv "$VENV_DIR" --system-site-packages
else
  info "Virtualenv already exists: $VENV_DIR"
fi

if ! check_python_gi "$VENV_DIR/bin/python"; then
  warn "Existing venv cannot import Gtk/Adw; recreating with --system-site-packages…"
  rm -rf "$VENV_DIR"
  python3 -m venv "$VENV_DIR" --system-site-packages
  check_python_gi "$VENV_DIR/bin/python" || {
    print_dep_help
    exit 1
  }
fi

info "Writing launcher: $LAUNCHER_PROJECT"
mkdir -p "$(dirname "$LAUNCHER_PROJECT")"
cat > "$LAUNCHER_PROJECT" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh — re-run ./install.sh after moving the project.
set -euo pipefail
export SPECTRE_DESKTOP_ROOT="$PROJECT_ROOT"
exec "$VENV_DIR/bin/python" "$PROJECT_ROOT/src/main.py" "\$@"
EOF
chmod +x "$LAUNCHER_PROJECT"

info "Installing user launcher: $LAUNCHER_USER"
mkdir -p "$(dirname "$LAUNCHER_USER")"
cp -f "$LAUNCHER_PROJECT" "$LAUNCHER_USER"
chmod +x "$LAUNCHER_USER"

if [[ ! -f "$ICON_SRC" ]]; then
  die "Icon not found: $ICON_SRC"
fi
info "Installing icon: $ICON_DST"
mkdir -p "$ICON_DST_DIR"
cp -f "$ICON_SRC" "$ICON_DST"

# Tray status icons (green lock / red unlock) — SVG theme + flat PNG for SNI
STATUS_SRC="$PROJECT_ROOT/data/icons/hicolor/scalable/status"
STATUS_DST="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/status"
if [[ -d "$STATUS_SRC" ]]; then
  info "Installing tray status icons → $STATUS_DST"
  mkdir -p "$STATUS_DST"
  cp -f "$STATUS_SRC"/*.svg "$STATUS_DST/" 2>/dev/null || true
fi
TRAY_PNG_SRC="$PROJECT_ROOT/data/icons/tray"
TRAY_PNG_DST="${XDG_DATA_HOME:-$HOME/.local/share}/spectre-desktop/tray-icons"
if [[ -d "$TRAY_PNG_SRC" ]]; then
  info "Installing tray PNGs → $TRAY_PNG_DST"
  mkdir -p "$TRAY_PNG_DST"
  cp -f "$TRAY_PNG_SRC"/*.png "$TRAY_PNG_DST/" 2>/dev/null || true
  # Also seed common hicolor sizes so Cinnamon resolves theme names like blueman
  for sz in 16 22 24 32 48; do
    hdir="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/${sz}x${sz}/status"
    mkdir -p "$hdir"
    if check_cmd rsvg-convert; then
      for svg in "$STATUS_SRC"/*.svg; do
        [[ -f "$svg" ]] || continue
        base=$(basename "$svg" .svg)
        rsvg-convert -w "$sz" -h "$sz" "$svg" -o "$hdir/${base}.png" 2>/dev/null || true
      done
    elif [[ -f "$TRAY_PNG_SRC/spectre-tray-unlocked.png" ]]; then
      # Fallback: copy 22/32 flat PNGs into theme dirs
      cp -f "$TRAY_PNG_SRC"/*.png "$hdir/" 2>/dev/null || true
    fi
  done
fi

if [[ ! -f "$DESKTOP_SRC" ]]; then
  die "Desktop template not found: $DESKTOP_SRC"
fi
info "Installing desktop entry: $DESKTOP_DST"
mkdir -p "$(dirname "$DESKTOP_DST")"
sed "s|@EXEC@|${LAUNCHER_USER}|g" "$DESKTOP_SRC" > "$DESKTOP_DST"
chmod 644 "$DESKTOP_DST"

if check_cmd desktop-file-validate; then
  desktop-file-validate "$DESKTOP_DST" || warn "desktop-file-validate reported issues"
fi

if check_cmd update-desktop-database; then
  update-desktop-database "${XDG_DATA_HOME:-$HOME/.local/share}/applications" 2>/dev/null || true
fi

if check_cmd gtk-update-icon-cache; then
  gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" 2>/dev/null || true
fi

info "Byte-compiling Python sources…"
"$VENV_DIR/bin/python" -m compileall -q "$PROJECT_ROOT/src" || warn "compileall failed (non-fatal)"

# Clearnet netns for Exclude apps — owned by Spectre core, not the Desktop tree.
# If spectre CLI is present, offer / attempt the one-time privileged setup.
setup_clearnet_hint() {
  cat <<'HINT'

Exclude apps (clearnet split tunnel) needs the Spectre core clearnet netns:

  spectre setup-clearnet
  # or from the spectre repo:
  #   ./scripts/setup-clearnet-privs.sh

That installs clearnet-run + clearnet-netns, creates the netns, sudoers, and
an optional boot unit. Safe to re-run (healthy netns = nft refresh only).
HINT
}

if check_cmd spectre; then
  if [[ -x /usr/local/libexec/spectre/clearnet-run ]] || [[ -x /usr/local/bin/clearnet-run ]]; then
    if [[ -e /run/netns/clearnet ]] || [[ -e /var/run/netns/clearnet ]]; then
      info "Clearnet exclude helper already installed (netns present)."
    else
      warn "clearnet-run is installed but netns “clearnet” is missing."
      info "Run: spectre setup-clearnet"
    fi
  else
    info "Clearnet exclude netns not installed yet."
    if [[ -t 0 ]]; then
      printf 'Run “spectre setup-clearnet” now? [y/N] '
      read -r ans || ans=""
      if [[ "${ans}" =~ ^[Yy]$ ]]; then
        if spectre setup-clearnet; then
          info "Clearnet netns setup finished."
        else
          warn "setup-clearnet failed — you can re-run: spectre setup-clearnet"
        fi
      else
        setup_clearnet_hint
      fi
    else
      setup_clearnet_hint
    fi
  fi
else
  warn "spectre CLI not on PATH — core install recommended for Exclude apps."
  setup_clearnet_hint
fi

cat <<EOF

────────────────────────────────────────────────────────
  ${APP_NAME} installed for your user account.
────────────────────────────────────────────────────────

  Application ID : ${APP_ID}
  Launcher       : ${LAUNCHER_USER}
  Desktop entry  : ${DESKTOP_DST}
  Icon           : ${ICON_DST}
  Project        : ${PROJECT_ROOT}

How to start
  • App menu: search for “${APP_NAME}”
  • Terminal: ${LAUNCHER_NAME}
  • Or:       ${LAUNCHER_PROJECT}

One-time system privileges (if not already done)
  • spectre setup-killswitch   # system routing + kill switch
  • spectre setup-clearnet     # clearnet netns for Exclude apps

Re-install after moving the project:
  cd ${PROJECT_ROOT} && ./install.sh

Uninstall:
  ./uninstall.sh
────────────────────────────────────────────────────────
EOF
